#!/usr/bin/env python
"""Emit the LaTeX table for the own-code superflip distance-20 optimality proof.

Reads the saved proof artifacts and the FlipUDSlice symmetry-table metadata and
writes ``thesis/tables/superflip_owncode_proof.tex``.  All numbers come from the
saved result files (the thesis invariant: no hand-typed benchmark numbers).

Source artifacts:
- results/processed/native_reid_optimal_superflip_probe_seed_2026_target19.json
  (the distance-20 proof: bound-19 exhausted, no solved leaf, no H48/Nissy)
- results/processed/native_reid_optimal_superflip_probe_seed_2026_target18.json
  (companion own-code proof that distance > 18)
- data/generated/phase1_sym_tables.json (FlipUDSlice 16-symmetry reduction)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _grp(value: int) -> str:
    return f"{value:,}".replace(",", "\\,")  # thin-space thousands separators


def _bool(value: bool) -> str:
    return "ναι" if value else "όχι"


def build_table() -> str:
    t19 = _load(ROOT / "results" / "processed" / "native_reid_optimal_superflip_probe_seed_2026_target19.json")
    t18 = _load(ROOT / "results" / "processed" / "native_reid_optimal_superflip_probe_seed_2026_target18.json")
    sym = _load(ROOT / "data" / "generated" / "phase1_sym_tables.json")

    sym_max = int(t19["sym_phase1_max_distance"])  # artifact-sourced, not hand-typed
    rows = [
        # \code uses \detokenize, so underscores inside \code{...} must be raw.
        ("Επιλυτής / λειτουργία", "\\code{kociemba_reid_optimal_ida} (\\code{--mode optimal-ida})"),
        ("Ευρετική", "FlipUDSlice φάση 1 με 16 συμμετρίες (έως %d) + τρεις άξονες $\\max(p_{ud},p_{rl},p_{fb})$"
            % sym_max),
        ("Μάσκα συμμετρίας ρίζας", "%s (σταθεροποιητής 48 στοιχείων του superflip)" % ", ".join(t19["root_symmetry_representatives"])),
        ("Χρήση H48/Nissy", _bool(bool(t19["uses_h48_or_nissy"]))),
        ("Στόχος φράγματος (μήκος)", str(int(t19["target_bound"]))),
        ("Κατάσταση", "\\code{%s}" % t19["status"]),
        ("Βρέθηκε φύλλο λύσης", _bool(bool(t19["solution_found"]))),
        ("Λήξη χρόνου / όριο κόμβων", "%s / %s" % (_bool(bool(t19["timed_out"])), _bool(bool(t19["node_limited"])))),
        ("Αποδεικνύει ότι δεν υπάρχει λύση $\\le$ 19", _bool(bool(t19["proves_no_solution_at_or_below_target"]))),
        ("Κόμβοι επέκτασης", _grp(int(t19["expanded_nodes"]))),
        ("Κόμβοι παραγωγής", _grp(int(t19["generated_nodes"]))),
        ("Χρόνος (8 νήματα)", "%.1f s" % float(t19["runtime_seconds"])),
        ("Συνοδευτική απόδειξη φράγματος 18", "αποδεικνύει ότι δεν υπάρχει λύση $\\le$ 18 (%s), %.1f s"
            % (_bool(bool(t18["proves_no_solution_at_or_below_target"])), float(t18["runtime_seconds"]))),
    ]

    sym_classes = int(sym.get("class_count", 64430))
    sym_twist = int(sym.get("twist_count", 2187))
    sym_entries = sym_classes * sym_twist
    rows.append((
        "Πίνακας συμμετρίας FlipUDSlice",
        "%s κλάσεις $\\times$ %s twist $=$ %s καταχωρήσεις φάσης 1 (ακριβής έως βάθος %d)"
        % (_grp(sym_classes), _grp(sym_twist), _grp(sym_entries), sym_max),
    ))

    lines = [
        "% Generated by scripts/generate_superflip_proof_table.py -- do not edit by hand.",
        "{\\small",
        "\\begin{tabular}{L{0.34\\textwidth}L{0.58\\textwidth}}",
        "\\toprule",
        "Μέγεθος & Τιμή \\\\",
        "\\midrule",
    ]
    for label, value in rows:
        lines.append(f"{label} & {value} \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "",
        "\\thesistablenote{\\code{lower_bound}: αποδεδειγμένο κάτω φράγμα μήκους, χωρίς χρήση εξωτερικών μηχανών (H48/Nissy).}",
        "}",
        "",
    ]
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", default="thesis")
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "thesis" / "tables" / "superflip_owncode_proof.tex",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    table = build_table()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(table, encoding="utf-8")
    try:
        shown = args.out.relative_to(ROOT)
    except ValueError:
        shown = args.out
    print(f"wrote {shown} ({len(table)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
